name: Deploy Kubernetes with Kubespray

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VAR_token: ${{ secrets.YC_TOKEN }}
  TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
  TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Для бэкенда S3
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (create infrastructure)
        run: terraform apply -auto-approve

      - name: Show inventory file
        run: cat inventory.ini

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clone Kubespray
        run: |
          if [ ! -d "kubespray" ]; then
            git clone https://github.com/kubernetes-sigs/kubespray.git
          fi

      - name: Install Ansible dependencies
        run: |
          cd kubespray
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Run Kubespray playbook
#        run: |
#          MASTER_IP=$(terraform output -raw master_ip)
#          cd kubespray
#          source venv/bin/activate
#          ansible-playbook -i ../inventory.ini cluster.yml -b --user ubuntu \
#          --extra-vars "{\"apiserver_cert_extra_sans\":[\"$MASTER_IP\"]}"

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Fetch kubeconfig from master node
        run: |
          sudo snap install yq
          MASTER_IP=$(terraform output -raw master_ip)
          echo $MASTER_IP
          ssh -o StrictHostKeyChecking=no ubuntu@$MASTER_IP << 'EOF'
            # Set the correct kubeconfig
            mkdir -p ~/.kube
            sudo cp /etc/kubernetes/admin.conf ~/.kube/config
            sudo chown $(id -u):$(id -g) ~/.kube/config            
            kubectl -n kube-system get cm kubeadm-config -o jsonpath='{.data.ClusterConfiguration}' > /tmp/kubeadm-config.yaml
            # Добавляем публичный IP в certSANs (если ещё нет)
            if ! yq eval ".apiServer.certSANs // [] | contains([\"$MASTER_IP\"])" /tmp/kubeadm-config.yaml | grep -q true; then
                yq eval ".apiServer.certSANs += [\"$MASTER_IP\"]" -i /tmp/kubeadm-config.yaml
                echo "IP $MASTER_IP добавлен в certSANs"
            else
                echo "IP $MASTER_IP уже присутствует"
            fi
            cat /tmp/kubeadm-config.yaml
            # Перегенерируем сертификат apiserver
            sudo mv /etc/kubernetes/pki/apiserver.crt /etc/kubernetes/pki/apiserver.crt.bak
            sudo mv /etc/kubernetes/pki/apiserver.key /etc/kubernetes/pki/apiserver.key.bak
            sudo kubeadm init phase certs apiserver --config=/tmp/kubeadm-config.yaml
            sudo cat /etc/kubernetes/admin.conf > ~/.kube/config
          EOF
          echo $MASTER_IP
          mkdir -p ~/.kube
          ssh -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "sudo cat /etc/kubernetes/admin.conf" > ~/.kube/config
          sed -i "s/127.0.0.1/$MASTER_IP/g" ~/.kube/config
          sed -i "s/10\.[0-9.]\+/$MASTER_IP/g" ~/.kube/config
          kubectl get nodes

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy kube-prometheus-stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --set grafana.service.type=NodePort \
            --set grafana.service.nodePort=31000
